# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\"\n\x0fServeClientArgs\x12\x0f\n\x07request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08leaderID\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\xa9\x01\n\x11\x41ppendEntriesArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderID\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1c\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0b.raft.Entry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\x12\x15\n\rleaseDuration\x18\x07 \x01(\x02\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"D\n\x05\x45ntry\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0c\n\x04term\x18\x04 \x01(\x05\"_\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateID\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"U\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x12\x1e\n\x16oldLeaderLeaseDuration\x18\x03 \x01(\x02\x32\xd0\x01\n\x08RaftNode\x12>\n\x0bServeClient\x12\x15.raft.ServeClientArgs\x1a\x16.raft.ServeClientReply\"\x00\x12\x44\n\rAppendEntries\x12\x17.raft.AppendEntriesArgs\x1a\x18.raft.AppendEntriesReply\"\x00\x12>\n\x0bRequestVote\x12\x15.raft.RequestVoteArgs\x1a\x16.raft.RequestVoteReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVECLIENTARGS']._serialized_start=20
  _globals['_SERVECLIENTARGS']._serialized_end=54
  _globals['_SERVECLIENTREPLY']._serialized_start=56
  _globals['_SERVECLIENTREPLY']._serialized_end=123
  _globals['_APPENDENTRIESARGS']._serialized_start=126
  _globals['_APPENDENTRIESARGS']._serialized_end=295
  _globals['_APPENDENTRIESREPLY']._serialized_start=297
  _globals['_APPENDENTRIESREPLY']._serialized_end=348
  _globals['_ENTRY']._serialized_start=350
  _globals['_ENTRY']._serialized_end=418
  _globals['_REQUESTVOTEARGS']._serialized_start=420
  _globals['_REQUESTVOTEARGS']._serialized_end=515
  _globals['_REQUESTVOTEREPLY']._serialized_start=517
  _globals['_REQUESTVOTEREPLY']._serialized_end=602
  _globals['_RAFTNODE']._serialized_start=605
  _globals['_RAFTNODE']._serialized_end=813
# @@protoc_insertion_point(module_scope)
